// <auto-generated />
namespace TimeTable2.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BookingType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookingType));
        
        string IMigrationMetadata.Id
        {
            get { return "201806140841232_BookingType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
